---
# WARNING
# This role provides a fresh installation of Magento on a new virtualhost and new database.
- name: mysql packages are present
  yum: 
    state=present
    name={{ item }}
  with_items:
    - MySQL-python
    - mysql

- name: document root exists
  file: 
    path={{ document_root }}
    state=directory
    mode=0775

- name: downloading magento
  get_url:
    url="https://3fb66be59b12e2b636cf-d69d20d277a755fdadf91611975f2510.ssl.cf5.rackcdn.com/magento-{{ magento_version }}.tar.gz"
    dest={{ document_root }}
    owner={{ domain_sftp_user }}
    group={{ vhost_user }}
    
- name: downloading sample content
  get_url:
    url="https://3fb66be59b12e2b636cf-d69d20d277a755fdadf91611975f2510.ssl.cf5.rackcdn.com/magento-sample-data-{{ magento_sample_data_version }}.tar.gz"
    dest={{ document_root }}
    owner={{ domain_sftp_user }}
    group={{ vhost_user }}
  when: placeholder_content == True
  
- name: unpacking magento
  unarchive: 
    src={{ document_root }}/magento-{{ magento_version }}.tar.gz
    dest={{ document_root }}
    copy=no
    
- name: unpacking sample content
  unarchive: 
    src={{ document_root }}/magento-sample-data-{{ magento_sample_data_version }}.tar.gz
    dest={{ document_root }}
    copy=no
  when: placeholder_content == True

- name: mysql client is updated
  template: 
    src=root/.my.cnf.j2
    dest=/root/.my.cnf
    owner=root
    group=root
    mode=0600

- name: database is present
  mysql_db: 
    state=present
    login_host={{ mysql_host_ip }}
    name={{ magento_db_name }}

- name: import sample mysql data
  mysql_db: 
    state=import
    login_host={{ mysql_host_ip }}
    name={{ magento_db_name }}
    target={{ document_root }}/magento-sample-data-{{ magento_sample_data_version }}/magento_sample_data_for_{{ magento_sample_data_version }}.sql
  when: placeholder_content == True

- name: copy core files
  shell: 
    chdir={{ document_root }}
    cp -a magento/{{ item.core }} .
  ignore_errors: yes
  with_items:
    - { core: '*', sample: 'media' }
    - { core: '.htaccess', sample: 'skin' }

- name: copy core sample files
  shell: 
    chdir={{ document_root }}
    cp -a magento-sample-data-{{ magento_sample_data_version }}/{{ item.sample }} .
  ignore_errors: yes
  with_items:
    - { core: '*', sample: 'media' }
    - { core: '.htaccess', sample: 'skin' }
  when: placeholder_content == True

# TEST SCRTIPS AND TOOLS HERE

- name: garbage collection
  shell: 
    chdir={{ document_root }}
    rm -rf {{ item }}
  ignore_errors: yes
  with_items: garbage_files

- name: ownership & directory permissions
  file: 
    state=directory
    recurse=yes
    path={{ document_root }}/
    owner={{ domain_sftp_user }}
    group={{ vhost_user }}
    mode=0755

- name: file mode permissions
  shell: 
    chdir={{ document_root }}
    find . -type f -exec chmod 644 {} \;

- name: installing magento...
  shell: 
    chdir={{ document_root }}
    chmod 500 mage &&
    ./mage mage-setup . &&
    ./mage config-set preferred_state stable &&
    ./mage install http://connect20.magentocommerce.com/community Mage_All_Latest --force &&
    php -f install.php -- --license_agreement_accepted "yes" --locale "en_US" --timezone "{{ tz }}" --default_currency "USD" --db_host {{ mysql_host_ip }} --db_name {{ magento_db_name }} --db_user {{ magento_db_user }} --db_pass {{ magento_db_password }} --url http://{{ vhost_domain }} --skip_url_validation --use_rewrites "yes" --use_secure "no" --secure_base_url https://{{ vhost_domain }} --use_secure_admin "no" --admin_firstname {{ magento_admin_fname }} --admin_lastname {{ magento_admin_lname }} --admin_email {{ magento_admin_email }} --admin_username {{ magento_admin_user }} --admin_password {{ magento_admin_pass }} &&
    php -f shell/indexer.php reindexall

- name: restart web stack
  service: 
    name={{ item }}
    state=restarted
  with_items:
    - nginx
    - php-fpm
