---
- name: php packages are installed
  yum: state=present name={{ item }}
  with_items:
    - "php"
    - "php-devel"
    - "php-imap"
    - "php-pdo"
    - "php-gd"
    - "php-mysql"
    - "php-mcrypt"
    - "php-xml"
    - "php-xmlrpc"
    - "php-soap"
    - "php-mbstring"
    - "php-pecl-lzf"
    - "php-pecl-apc"
    - "php-pecl-redis"
    - "php-pecl-memcache"

- name: php modules are configured
  template: 
    src={{ item.src }}
    dest={{ item.dest }}
    backup=yes
  with_items:
    - { src: 'etc/php.ini.j2', dest: '/etc/php.ini' }
    - { src: 'etc/php.d/apc.ini.j2', dest: '/etc/php.d/apc.ini' }
    - { src: 'etc/php.d/redis.ini.j2', dest: '/etc/php.d/redis.ini' }
